export const IDL = {
  address: "FGBieAeHERm7CJxtXsicQ7NaQ4FqsDixSwmMqKhovfpH",
  metadata: { name: "zalary", version: "0.1.0", spec: "0.1.0" },
  instructions: [
    {
      name: "createOrganization",
      discriminator: [60,173,177,39,122,23,68,185],
      accounts: [
        { name: "organization", writable: true },
        { name: "treasury", writable: true },
        { name: "usdcMint" },
        { name: "authority", writable: true, signer: true },
        { name: "systemProgram" },
        { name: "tokenProgram" },
        { name: "rent" },
      ],
      args: [{ name: "name", type: "string" }],
    },
    {
      name: "addEmployee",
      discriminator: [14,82,239,156,50,90,189,61],
      accounts: [
        { name: "organization", writable: true },
        { name: "employee", writable: true },
        { name: "authority", writable: true, signer: true },
        { name: "systemProgram" },
      ],
      args: [
        { name: "wallet", type: "pubkey" },
        { name: "encryptedSalary", type: { array: ["u8", 64] } },
      ],
    },
    {
      name: "removeEmployee",
      discriminator: [16,10,234,98,224,29,67,64],
      accounts: [
        { name: "organization", writable: true },
        { name: "employee", writable: true },
        { name: "authority", signer: true },
      ],
      args: [],
    },
    {
      name: "updateSalary",
      discriminator: [201,74,241,234,152,230,48,234],
      accounts: [
        { name: "organization" },
        { name: "employee", writable: true },
        { name: "authority", signer: true },
      ],
      args: [{ name: "newEncryptedSalary", type: { array: ["u8", 64] } }],
    },
    {
      name: "fundTreasury",
      discriminator: [71,154,45,220,206,32,174,239],
      accounts: [
        { name: "organization" },
        { name: "treasury", writable: true },
        { name: "funderTokenAccount", writable: true },
        { name: "usdcMint" },
        { name: "funder", writable: true, signer: true },
        { name: "tokenProgram" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "runPayroll",
      discriminator: [224,128,206,1,134,16,133,5],
      accounts: [
        { name: "organization", writable: true },
        { name: "treasury", writable: true },
        { name: "employee", writable: true },
        { name: "employeeTokenAccount", writable: true },
        { name: "payrollRun", writable: true },
        { name: "usdcMint" },
        { name: "authority", writable: true, signer: true },
        { name: "pauseCheck" },
        { name: "systemProgram" },
        { name: "tokenProgram" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "setAuditor",
      discriminator: [90,12,154,66,85,118,8,107],
      accounts: [
        { name: "organization" },
        { name: "auditor", writable: true },
        { name: "authority", writable: true, signer: true },
        { name: "systemProgram" },
      ],
      args: [{ name: "auditor", type: "pubkey" }],
    },
    {
      name: "clearAuditor",
      discriminator: [101,76,104,177,40,11,216,136],
      accounts: [
        { name: "organization" },
        { name: "auditor", writable: true },
        { name: "authority", writable: true, signer: true },
      ],
      args: [],
    },
    {
      name: "pauseOrganization",
      discriminator: [157,149,174,224,109,150,45,144],
      accounts: [
        { name: "organization" },
        { name: "pause", writable: true },
        { name: "authority", writable: true, signer: true },
        { name: "systemProgram" },
      ],
      args: [],
    },
    {
      name: "resumeOrganization",
      discriminator: [69,180,108,93,249,214,15,1],
      accounts: [
        { name: "organization" },
        { name: "pause", writable: true },
        { name: "authority", writable: true, signer: true },
      ],
      args: [],
    },
    {
      name: "claimFunds",
      discriminator: [145,36,143,242,168,66,200,155],
      accounts: [
        { name: "organization" },
        { name: "employee" },
        { name: "escrowTokenAccount", writable: true },
        { name: "claimerTokenAccount", writable: true },
        { name: "usdcMint" },
        { name: "claimer", writable: true, signer: true },
        { name: "tokenProgram" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "verifyWorldId",
      discriminator: [215,9,170,36,225,31,35,175],
      accounts: [
        { name: "organization" },
        { name: "employee", writable: true },
        { name: "claimer", signer: true },
      ],
      args: [{ name: "nullifierHash", type: { array: ["u8", 32] } }],
    },
    {
      name: "closeOrganization",
      discriminator: [223,179,142,148,80,216,32,61],
      accounts: [
        { name: "organization", writable: true },
        { name: "treasury", writable: true },
        { name: "authority", writable: true, signer: true },
        { name: "tokenProgram" },
      ],
      args: [],
    },
    {
      name: "withdrawTreasury",
      discriminator: [40,63,122,158,144,216,83,96],
      accounts: [
        { name: "organization" },
        { name: "treasury", writable: true },
        { name: "authorityTokenAccount", writable: true },
        { name: "usdcMint" },
        { name: "authority", signer: true },
        { name: "tokenProgram" },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
  ],
  accounts: [
    { name: "Organization", discriminator: [145,38,152,251,91,57,118,160] },
    { name: "Employee", discriminator: [98,238,61,252,130,77,105,67] },
    { name: "PayrollRun", discriminator: [11,197,215,124,64,255,82,248] },
    { name: "OrgAuditor", discriminator: [148,227,193,218,102,146,114,212] },
  ],
  types: [
    {
      name: "Organization",
      type: {
        kind: "struct",
        fields: [
          { name: "authority", type: "pubkey" },
          { name: "name", type: "string" },
          { name: "treasury", type: "pubkey" },
          { name: "employeeCount", type: "u32" },
          { name: "totalDisbursed", type: "u64" },
          { name: "payrollCount", type: "u32" },
          { name: "createdAt", type: "i64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Employee",
      type: {
        kind: "struct",
        fields: [
          { name: "organization", type: "pubkey" },
          { name: "wallet", type: "pubkey" },
          { name: "encryptedSalary", type: { array: ["u8", 64] } },
          { name: "status", type: { defined: { name: "EmployeeStatus" } } },
          { name: "worldIdVerified", type: "bool" },
          { name: "nullifierHash", type: { array: ["u8", 32] } },
          { name: "addedAt", type: "i64" },
          { name: "lastPaidAt", type: "i64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "PayrollRun",
      type: {
        kind: "struct",
        fields: [
          { name: "organization", type: "pubkey" },
          { name: "initiator", type: "pubkey" },
          { name: "employeeCount", type: "u32" },
          { name: "totalAmount", type: "u64" },
          { name: "timestamp", type: "i64" },
          { name: "status", type: { defined: { name: "PayrollStatus" } } },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "EmployeeStatus",
      type: {
        kind: "enum",
        variants: [{ name: "Active" }, { name: "Pending" }, { name: "Inactive" }],
      },
    },
    {
      name: "OrgAuditor",
      type: {
        kind: "struct",
        fields: [
          { name: "auditor", type: "pubkey" },
          { name: "setAt", type: "i64" },
        ],
      },
    },
    {
      name: "PayrollStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Processing" },
          { name: "Confirmed" },
          { name: "Failed" },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: "Unauthorized", msg: "You are not authorized to perform this action" },
    { code: 6001, name: "NameTooLong", msg: "Organization name too long (max 64 characters)" },
    { code: 6002, name: "EmployeeNotActive", msg: "Employee is not active" },
    { code: 6003, name: "EmployeeAlreadyActive", msg: "Employee is already active" },
    { code: 6004, name: "InsufficientFunds", msg: "Insufficient funds in treasury" },
    { code: 6005, name: "InvalidAmount", msg: "Invalid amount" },
    { code: 6006, name: "NoActiveEmployees", msg: "No active employees for payroll" },
    { code: 6007, name: "PayrollAlreadyProcessed", msg: "Payroll already processed" },
    { code: 6008, name: "Overflow", msg: "Arithmetic overflow" },
    { code: 6009, name: "OrganizationPaused", msg: "Organization payroll is paused" },
  ],
} as const
